name: jkitsakis-viber
version: '1.0'
summary: Free and secure calls and messages to anyone, anywhere
description: | 
  Authentic conversations, the way you like them
  Deepen your relationships with Viber’s wide range 
  of communication features.
  This is an unofficial snap package for Viber based on viber.deb


grade: devel
confinement: strict

apps:
  jkitsakis-viber:
    command: desktop-launch $SNAP/opt/viber/Viber
    desktop: usr/share/applications/my-app.desktop
    plugs:
     - x11
     - desktop
     - desktop-legacy
     - wayland
     - unity7
     - network-bind
     - network-observe
     - home
     - opengl
     - gsettings

parts:
  jkitsakis-viber:
    plugin: dump
    source: http://download.cdn.viber.com/cdn/desktop/Linux/viber.deb
    source-type: deb
    after: [desktop-qt5]
    build-attributes: [keep-execstack]
    stage-packages: 
      - xdg-utils
      - libxss1
      - libpulse0
      - libpulse0
      - libcurl3-gnutls
      - libcurl3